name: 'Build DEB repo'
description: |
  Build a DEB repository for the specified packages
inputs:
  label:
    desctiption: |
      Project name
    required: true
  origin:
    desctiption: |
      Project origin name or domain name
    required: false
  desc:
    desctiption: |
      Repository description
    required: true
    default: ""
  codename:
    desctiption: |
      Project target distro codename
    required: true
    default: unstable
  architectures:
    desctiption: |
      List of architectures of packages
    required: true
    default: |
      source
      amd64
  components:
    desctiption: |
      Repository components
    required: true
    default: main
  udeb_components:
    desctiption: |
      Repository UDeb components
    required: true
    default: main
  gpg_signing_key:
    description: |
      The GPG key to use for signing the package in the repo
    required: false
  maintainer:
    description: |
      The maintainer of the packages signed with gpg_signing_key
    required: false
  from_metadatas:
    description: |
      List of package metadata to include in the repository
    required: true
  from_deb_packages:
    description: |
      List of DEB packages to include in the repository
    required: true
    default: ""
outputs:
  placeholder:
    description: ""
    value: true
runs:
  using: "composite"
  steps:
    - name: Generate distributions file
      env:
        GPG_SIGNING_KEY: ${{ inputs.gpg_signing_key }}
        MAINTAINER: ${{ inputs.maintainer }}
      run: |
        ORIGIN='${{ inputs.origin }}'
        [ ! $ORIGIN ] && ORIGIN='${{ inputs.label }}'
        ARCH=$(echo '${{ inputs.architectures }}' | tr '\n' ' ')
        COMPONENT=$(echo '${{ inputs.components }}' | tr '\n' ' ')
        UDEB_COMPONENT=$(echo '${{ inputs.udeb_components }}' | tr '\n' ' ')
        mkdir -p dist/conf
        echo "Origin: $ORIGIN" >>dist/conf/distributions
        echo 'Label: ${{ inputs.label }}' >>dist/conf/distributions
        echo 'Codename: ${{ inputs.codename }}' >>dist/conf/distributions
        echo "Architectures: $ARCH" >>dist/conf/distributions
        echo "Components: $COMPONENT" >>dist/conf/distributions
        echo "UDebComponents: $UDEB_COMPONENT" >>dist/conf/distributions
        echo 'Description: ${{ inputs.desc }}' >>dist/conf/distributions
        if [ "$GPG_SIGNING_KEY" ]; then
          echo "$GPG_SIGNING_KEY" | gpg --import
          echo $MAINTAINER
          echo "DEBEMAIL='$(echo $DEB_MAINTAINER | awk -F '<' '{print $2}' | awk -F '>' '{print $1}')'" >>"$GITHUB_OUTPUT"
          echo "DEBFULLNAME='$(echo $DEB_MAINTAINER | awk -F '<' '{print $1}')'" >>"$GITHUB_OUTPUT"
          source "$GITHUB_OUTPUT"
          KEY_FINGERPRINT=$(gpg --list-secret-key --with-subkey-fingerprint | grep -A3 "$MAINTAINER" | tail -1)
          echo $KEY_FINGERPRINT
          echo "SignWith: $KEY_FINGERPRINT" >>dist/conf/distributions
        fi
        cat dist/conf/distributions
      shell: bash

    - name: Copy source scripts
      run: cp -r ${{ github.action_path }}/{repo-download,debsign}.sh .
      shell: bash

    - name: Getting need packages
      run: |
        sudo apt update && sudo apt -y upgrade
        sudo apt install -y aria2 reprepro gnupg2
      shell: bash

    - name: Generate repo artifact
      env:
        METADATA_LINKS: ${{ inputs.from_metadatas }}
        DEB_LINKS: ${{ inputs.from_deb_packages }}
        RELEASE: ${{ inputs.codename }}
      run: |
        echo $METADATA_LINKS
        echo $DEB_LINKS
        echo $RELEASE
        export METADATA_LINKS DEB_LINKS RELEASE
        ./repo-download.sh
      shell: bash

    - name: Compress build files
      run: zip -r dist.zip dist
      shell: bash

    - name: Clean up
      run: rm -rf dist
      shell: bash
